[package]
name = "prefab"
version = "0.1.0"
authors = ["Tom Godkin <thgodkin@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
nix = "0.13"
